@api = http://localhost:5748/api

GET {{api}}/albums HTTP/1.1
###

POST {{api}}/albums HTTP/1.1

Content-Type: application/json
{
    "name" : "Album 1"
}
###

PUT {{api}}/albums/1 HTTP/1.1
###

GET {{api}}/albums/1 HTTP/1.1
###

DELETE {{api}}/albums/1 HTTP/1.1
###